
SELECT GAME_ID, AWAY_TEAM_ID, HOME_TEAM_ID, AWAY_SCORE_CT, HOME_SCORE_CT, INN_CT, MINUTES_GAME_CT 
FROM games WHERE INN_CT = 9
ORDER BY MINUTES_GAME_CT DESC LIMIT 50;


SELECT GAME_ID, AWAY_TEAM_ID, HOME_TEAM_ID, AWAY_SCORE_CT, HOME_SCORE_CT, INN_CT, MINUTES_GAME_CT 
FROM games WHERE INN_CT = 9 AND ( HOME_TEAM_ID = 'TOR' OR AWAY_TEAM_ID = 'TOR' ) 
ORDER BY MINUTES_GAME_CT DESC LIMIT 50;


SELECT GAME_ID AS 'Game', PIT_ID AS 'Pitcher', COUNT(*) AS 'Strikeouts' 
FROM events WHERE PIT_ID = 'clemr001' AND EVENT_CD = '3'
GROUP BY GAME_ID ORDER BY COUNT(*) DESC LIMIT 50;


